#pragma once
#define LV_COLOR_DEPTH 32
#define LV_USE_OS LV_OS_NONE
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_LOG 0
#define LV_USE_SNAPSHOT 1
#define LV_USE_LODEPNG 1
#define LV_BUILD_EXAMPLES 0
#define LV_BUILD_DEMOS 0
